package com.syncduo.server.enums;

public enum FileEventTypeEnum {

    SOURCE_FOLDER_FILE_CREATED,

    SOURCE_FOLDER_FILE_CHANGED,

    SOURCE_FOLDER_FILE_DELETED,

    INTERNAL_FOLDER_FILE_CREATED,

    INTERNAL_FOLDER_FILE_CHANGED,

    INTERNAL_FOLDER_FILE_DELETED,

    CONTENT_FOLDER_FILE_CREATED,

    CONTENT_FOLDER_FILE_CHANGED,

    CONTENT_FOLDER_FILE_DELETED
}
